zfs_snapshot_pool: mpool

zfs_snapshot_schedules:
  - frequency: hourly
    calendar: "*:00:00"
    keep: 24
  - frequency: daily
    calendar: "*-*-* 00:00:00"
    keep: 30
  - frequency: weekly
    calendar: "Sun *-*-* 00:00:00"
    keep: 12
  - frequency: monthly
    calendar: "*-*-01 00:00:00"
    keep: 12
