- hosts: zwave.lab.nkontur.com
  roles:
  - role: fetch-vault-secrets
    vars:
      fetch_ssh_ca_key: true
  - role: claude-user
    vars:
      claude_user_name: claude-zwave
      claude_user_group: claude-zwave
      claude_user_principal: claude-zwave
  - configure-zwave
  - configure-snapclient
  - configure-docker
  - deploy-compose
  become: yes

