apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: pOh_O4GGz
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: homelab
      defaultBucket: metrics
    secureJsonData:
      token: $INFLUXDB_TOKEN
    isDefault: true
    editable: true
