apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: https://loki.lab.nkontur.com
    isDefault: false
    editable: true
    basicAuth: true
    basicAuthUser: "{{ vault_loki_push_username }}"
    secureJsonData:
      basicAuthPassword: "{{ vault_loki_push_password }}"
    jsonData:
      tlsSkipVerify: true
